name: Deploy Medusa Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      id: build-image
      run: |
        REPO_URI=${{ secrets.ECR_REPOSITORY_URI }}
        IMAGE_TAG=latest
        docker build -t $REPO_URI:$IMAGE_TAG .
        docker push $REPO_URI:$IMAGE_TAG

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ecs_task_definition.json
        service: medusa-service
        cluster: medusa-cluster
        wait-for-service-stability: true
